### PR TITLE
fix: apply dark mode to markdown table (#862)

### LINKED ISSUE #862: Markdown tables should be dark when in darkmode
Here is a proposal you can use for testing https://snapshot.org/#/samuv.eth/proposal/QmdWeZ7dCP5XufTSjZ8ZEwLzpH82AU4CprshYb8529VVRP

### PR DESCRIPTION
**Pull request by 69hunter**
Fixes #862  .

Changes proposed in this pull request:
- Use variable in markdown table
- Alternate color for light mode and dark mode markdown table

### CODE REVIEW

File: src/components/Ui/Markdown.vue [hunk 1]
```diff
@@ -266,16 +266,17 @@ const markdown = computed(() => {
...
+.markdown-body table thead tr,
+.markdown-body table tbody tr:nth-child(2n) {
+  background-color: var(--bg-color);
   border-top: 1px solid #c6cbd1;
 }
 
-.markdown-body table tr:nth-child(2n) {
-  background-color: #f6f8fa;
+.markdown-body table tbody tr {
+  background-color: var(--bg-darker-color);
```
Comment (samuveth) [inline src/components/Ui/Markdown.vue:279]: using a new `var` will not work with skins here https://github.com/snapshot-labs/snapshot-spaces/tree/master/skins

**Review by samuveth — APPROVED** [review]
