### PR TITLE
fix: Add support for delegation related strategies on delegation page

### LINKED ISSUE #4659: [BUG] - Delegation page not working
### Briefly describe the bug.

Delegation page doesn't work for balancer https://snapshot.org/#/delegate/balancer.eth

### How can we reproduce the bug?

Originally reported here: https://discord.com/channels/707079246388133940/1225090260648595532/1225090649972543519
image

### What is the expected behaviour?

Should be able to delegate

### Can you attach screenshots?

_No response_

### Can you provide your device specific details below?

_No response_

### PR DESCRIPTION
**Pull request by ChaituVR**
Closes #4659 

Previously only delegation strategy works on delegation page, this PR will add `erc20-balance-of-delegation` and `delegation-with-cap` as these strategies are very similar to delegation strategy and should not create any problems

## How to test:
- Go to https://snapshot-2xwxdbhwj-snapshot.vercel.app/#/delegate/balancer.eth and you should see top delegates

### CODE REVIEW

File: src/views/DelegateView.vue [hunk 1]
```diff
@@ -121,9 +121,15 @@ async function getDelegationsAndDelegates() {
   }
 }
 
+const delegationStrategies = [
+  'delegation',
+  'erc20-balance-of-delegation',
+  'delegation-with-cap'
+];
```
Comment (ChaituVR) [inline src/views/DelegateView.vue:128]:
```suggestion
const delegationStrategies = [
  'delegation',
  'erc20-balance-of-delegation',
  'delegation-with-cap',
  'delegation-with-overrides'
];
```

**Review by wa0x6e — APPROVED** [review]
utAck
