### PR TITLE
fix(): use router-link (a tags) for better accessibility

### LINKED ISSUE #625: These links should be clickable with the mouse wheel
When i click on these link with the mouse wheel (to open it on a new tab) it doesnt work, we should fix that.

image

### PR DESCRIPTION
**Pull request by harshmaur**
Fixes #625

### CODE REVIEW

File: src/components/MainSidebar.vue [hunk 1]
```diff
@@ -38,12 +38,14 @@ onMounted(() => {
   >
     <div class="flex flex-col h-full overflow-scroll menu-tabs">
       <div class="min-h-[78px] h-[78px] flex items-center justify-center">
-        <Icon
-          @click="$router.push({ name: 'home' })"
-          size="36"
-          name="snapshot"
-          class="text-snapshot cursor-pointer"
-        />
+        <router-link :to="{ name: 'home' }">
```
Comment (samuveth) [inline src/components/MainSidebar.vue:41]: Why do we need to link to route twice here?

Comment (harshmaur) [reply src/components/MainSidebar.vue:41]: Ah forgot to remove it from icon.

**Review by samuveth — APPROVED** [review]
LGTM
