### PR TITLE
Fix bugs, start refactor settings and add typescript

### LINKED ISSUE #2452: Settings not updating after being saved
https://discord.com/channels/707079246388133940/747050056422785055/979603800438476831

### PR DESCRIPTION
**Pull request by samuveth**
Part of #1925
Fixes #2452

Changes:
- Fix edit controller placeholder and other bugs with route for ENS address
- Fix settings not reloading after saving settings or edit controller
- Add typescript to settings view

### CODE REVIEW

File: src/views/SpaceSettings.vue [hunk 1]
```diff
@@ -46,27 +47,49 @@ const modalPluginsOpen = ref(false);
...
+  skin: ''
+};
+
+const form = ref(clone(spaceObject));
 
 const validate = computed(() => {
-  if (form.value.terms === '') delete form.value.terms;
-  if (form.value.avatar === '') delete form.value.avatar;
-  if (form.value.website === '') delete form.value.website;
+  const formClone = formatSpace(form.value);
```
Comment (samuveth) [inline src/views/SpaceSettings.vue:90]:
```suggestion
  const formattedForm = formatSpace(form.value);
```

File: src/views/SpaceSettings.vue [hunk 2]
```diff
@@ -46,27 +47,49 @@ const modalPluginsOpen = ref(false);
...
 
-  return validateSchema(schemas.space, form.value);
+  return validateSchema(schemas.space, formClone);
```
Comment (samuveth) [inline src/views/SpaceSettings.vue:92]:
```suggestion
  return validateSchema(schemas.space, formattedForm);
```
