### PR TITLE
fix: duplicate insert in texareaarray component

### LINKED ISSUE #1609: Able to add duplicate authors in settings
**Describe the bug**

Able to add duplicate authors in settings

**To Reproduce**
1. Go to settings and add the same address multiple times in authors
2. Click save

**Expected behavior**

Remove duplicates

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by bigint**
Fixes #1609

https://user-images.githubusercontent.com/69431456/152187770-d1720adc-11af-4bb9-9dae-f9caba81e792.mov

### CODE REVIEW

**Comment by bigint** [comment]
cc @bonustrack @samuveth

File: src/components/TextareaArray.vue [hunk 1]
```diff
@@ -16,7 +16,10 @@ function handleInput() {
     .replace(/;/g, ' ')
     .split(' ')
     .map(item => item.trim())
-    .filter(item => !!item);
+    .filter(item => !!item)
+    .filter((item, index, array) => {
+      return array.indexOf(item) == index;
+    });
```
Comment (mktcode) [inline src/components/TextareaArray.vue:22]:
```suggestion
    .filter(item => !!item)
    .filter((item, index, array) => array.indexOf(item) === index);
```

**Review by mktcode — APPROVED** [review]
Good catch! Thanks! :)
