### PR TITLE
fix: wrong token when switching accounts in comment box

### LINKED ISSUE #1550: CommentBox: Wrong token when switching accounts
The commentBox plugin stores a token in local storage but when switching accounts that old one is still used, causing an error.

image

1. Write a comment -> sign message -> token stored in local storage
2. Switch eth account, write another comment -> error

The storage value needs the account address as part of the key name.

### PR DESCRIPTION
**Pull request by bigint**
Fixes #1550

https://user-images.githubusercontent.com/69431456/151702815-6c0d394b-5b98-422c-badb-ba1de398696c.mov

### CODE REVIEW

**Comment by bigint** [comment]
cc @samuveth @mktcode

File: components.d.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ declare module 'vue' {
     PluginSafeSnapInputMethodParameter: typeof import('./src/components/Plugin/SafeSnap/Input/MethodParameter.vue')['default']
     PluginSafeSnapModalOptionApproval: typeof import('./src/components/Plugin/SafeSnap/Modal/OptionApproval.vue')['default']
     PluginSafeSnapSafeTransactions: typeof import('./src/components/Plugin/SafeSnap/SafeTransactions.vue')['default']
+    PluginSafeSnapTooltip: typeof import('./src/components/Plugin/SafeSnap/Tooltip.vue')['default']
```
Comment (bigint) [inline components.d.ts:74]:
```suggestion
```

**Review by mktcode — APPROVED** [review]
Tested. Works. Thanks!
