### PR TITLE
fix(UX): fix keyboard navigation

### LINKED ISSUE #3707: [BUG] - Broken keyboard navigation
### Briefly describe the bug.

Not a serious bug, more of an UX issue: the keyboard navigation seems broken in some part of the site

### How can we reproduce the bug?

1. Go to the homepage
2. Use the keyboard `TAB` key to scroll through the links

- You will notice that some links are focused twice: this is because some `<button>` element are nested inside another `<button>` or `<a>` (both are not valid HTML5). This is the case for all links/buttons with a popover.
- You will also notice that sometime, the focus disappear, because the focused element does not have a focus style.
- The space links in the left sidebar are never focus-able with keyboard navigation, as they are neither `<button>` nor `<link>` element.
- The invalid html also seems to break the tab navigation inside the popover. `TAB` never go inside the popover, even though it should be supported, as described in the headlessui docs.

### What is the expected behaviour?

Navigating the page links with the keyboard should jump/focus from one link to the next, and not skip any links, nor focus the same link twice (because of nested `button`/`a`).

Keyboard navigation should also be able to navigate inside popover content.

One way to fix that will be to slap `tabindex="0|-1"` anywhere there's an issue, but the most appropriate fix will be to remove the nested `button`/`a` whenever possible, by maybe editing the <ButtonSidebar> to return a div/other element if asked via props (`as:`), instead of a button

### Can you attach screenshots?

_No response_

### Can you provide your device specific details below?

This is reproducible from any desktop browser

### PR DESCRIPTION
**Pull request by wa0x6e**
### Issues
This PR fixed UX issues where keyboard navigation is not intuitive and fluid.

Fixes #3707 

### Changes 

1. Fix most of the nested `<button>` inside `<a>/<button>`, removing the redundant focus when navigating through the links, otherwise, disable the redundant focus by adding `tabindex="-1"` to the element without navigation event
2. Converting `<div>` with onClick event to `<a>` or `<button>`, to make them focusable, whenever possible
3. Make navigation element visually focusable (remove the `outline-none` class)
4. Fix popover link (e.g. TheNavbar component): auto-focus element inside the popover on open

### How to test

1. Open any pages, and navigate through the page with the keyboard with `TAB`
2. The focus should jump from one link to the next logical one

### To-Do
Not everything are fixed, only the most used components are fixed for now.
Some more advanced pages, such as plugins, are not fixed yet.

### Self-review checklist
- [x] I have performed a full self-review of my changes
- [x] I have tested my changes on a preview deployment
- [ ] I have tested my changes on a custom domain
- [ ] I have run end-to-end tests `yarn cypress:test:e2e`, and they have passed

### Additional notes or considerations
Nothing new is introduced, the worst that could happen are some broken links.

Keyboard navigation is still broken with modal, opening a modal does auto move the next `TAB` focus inside the modal. This is due to the custom modal implementation, which does not implement the necessary [focus helper](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/utils/focus-management.ts) found in the headlessui modal

UI-wise, some focus style are not matching the button style (missing the rounded corner), as the focus is on the outer element, without the button style.

There's some unrelate html class sorting changes, automatically done by prettier

There's also some redundancy by setting `@click` and `@keypress`. Is there a way to set both of them at once?

### CODE REVIEW

**Comment by samuveth** [comment]
Please request a review from @j0hnfl0w and me when ready

File: src/components/TheSidebar.vue [hunk 1]
```diff
@@ -65,23 +65,24 @@ watch(
...
+    <div class="mt-2 px-2">
+      <router-link v-slot="{ href }" custom :to="{ name: 'timeline' }">
+        <ButtonSidebar
+          v-tippy="{
+            content: 'Timeline',
+            placement: 'right',
+            delay: [750, 0],
+            touch: ['hold', 500]
+          }"
+          :href="href"
```
Comment (samuveth) [inline src/components/TheSidebar.vue:83]: I don't see an `href` prop on the `ButtonSidebar` component

File: src/components/ButtonSidebar.vue [hunk 2]
```diff
@@ -1,15 +1,20 @@
 <script setup lang="ts">
-defineProps<{
-  isDisabled?: boolean;
-}>();
+withDefaults(
```
Comment (samuveth) [inline src/components/ButtonSidebar.vue:2]: This component is somewhat unclear:

1.  of labeling it as a "sidebar" button, it would be more appropriate to call it a "fully rounded button," given its usage in various locations. A name change should be considered.
2. If the component is referred to as a button, it should use the proper <button> element instead of <a> or both. Alternatively, if it functions as a link, it might be better to rename it as "link."
3. To reduce redundancy, it might be beneficial to refactor this component into either the BaseButton or BaseLink component, depending on its primary function.

File: src/components/SpaceProposalVotesList.vue [hunk 3]
```diff
@@ -36,13 +36,13 @@ onMounted(async () => {
...
   >
     <template v-if="props.proposal.state === 'closed'" #button>
-      <BaseButtonIcon>
-        <LoadingSpinner v-if="isDownloadingVotes" />
-        <i-ho-download
-          v-else
-          v-tippy="{ content: 'Download as CSV' }"
-          @click="downloadVotes(proposal.id, proposal.space.id)"
-        />
+      <BaseButtonIcon v-if="isDownloadingVotes" :loading="true" />
```
Comment (samuveth) [inline src/components/SpaceProposalVotesList.vue:39]: Why use a second `BaseButtonIcon` for the loading.

**Comment by wa0x6e** [comment]
- SidebarButton has been renamed to RoundButton, to reflect its purpose
- Prefer use of `button` over `a` when possible, to avoid the redundant `@keypress` event

File: src/components/ButtonTheme.vue [hunk 4]
```diff
@@ -3,12 +3,12 @@ const { toggleUserTheme, getThemeIcon } = useSkin();
 </script>
 
 <template>
-  <ButtonSidebar
+  <RoundButton
```
Comment (samuveth) [inline src/components/ButtonTheme.vue:6]: To maintain consistency and improve readability, we should adhere to the [Vue style guide](https://vuejs.org/style-guide/rules-strongly-recommended.html) for naming components. The guide recommends a specific naming convention that helps developers understand the hierarchy and relationships between components more easily. For example, instead of using the component name <RoundButton />, we should rename it to <ButtonRound />. If the button is a base component, it should be named <BaseButtonRound>. This approach allows us to group related components together, designate base components clearly, and quickly identify their purpose within the application.

File: src/components/RoundButton.vue [hunk 5]
```diff
@@ -1,20 +1,16 @@
...
-withDefaults(
-  defineProps<{
-    isDisabled?: boolean;
-    as?: string;
-  }>(),
-  { as: 'button' }
-);
+defineProps<{
+  isDisabled?: boolean;
+  as?: string;
```
Comment (samuveth) [inline src/components/RoundButton.vue:4]: Is this `as` prop still needed?

**Comment by samuveth** [comment]
Great work! @wa0x6e
