### PR TITLE
Fix delegations page bug with new d-graph

### LINKED ISSUE #2124: Issue with new D subgraph and delegation
Upgrade to d-graph is causing the query with empty string as space to return nothing, resulting in missing delegations.

Before
image

After 
image

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #2124

### CODE REVIEW

File: src/helpers/delegation.ts [hunk 1]
```diff
@@ -37,13 +37,19 @@ export async function getDelegators(network: string, address: string) {
...
-export async function getDelegatesBySpace(network: string, space: string) {
+export async function getDelegatesBySpace(
+  network: string,
+  space: string | undefined
+) {
+  const where = space
+    ? {
+        space
+      }
+    : {};
```
Comment (ChaituVR) [inline src/helpers/delegation.ts:48]: @samuveth Passing `null` instead of empty string works with this new subgraph to get global delegations, sorry for not updating you about this :) didn't know we query it here too,

**Review by ChaituVR — CHANGES_REQUESTED** [review]

File: src/helpers/delegation.ts (hunk 1 above)
Comment (samuveth) [reply src/helpers/delegation.ts:48]: Ok thanks

**Comment by samuveth** [comment]
@ChaituVR like that?

File: src/views/Delegate.vue [hunk 2]
```diff
@@ -157,7 +157,7 @@ async function getDelegatesWithScore() {
   delegatesLoading.value = true;
   try {
     const delegationsRes = await Promise.all([
-      getDelegatesBySpace(space.value.network, ''),
+      getDelegatesBySpace(space.value.network, null),
       getDelegatesBySpace(space.value.network, space.value.id)
     ]);
```
Comment (mktcode) [inline src/views/Delegate.vue:162]: Not sure I understand this. Isn't the space param unnecessary? It calls it with and without a space and then merges the results together. But the function is called `getDelegatesBySpace`, so I'm a bit confused.

Comment (samuveth) [reply src/views/Delegate.vue:162]: There are global delegations and space level delegations. To get both we need to query like this.

Comment (samuveth) [reply src/views/Delegate.vue:162]: Space global delegations will not be included if queried by space and vise versa.

Comment (mktcode) [reply src/views/Delegate.vue:162]: Yea I mean.... can't you just remove the where? As far as I can see this function is used only here for this one purpose.

Comment (mktcode) [reply src/views/Delegate.vue:162]: Oh I just saw that this is just meant to hotfix stable... approved. :D

**Review by mktcode — APPROVED** [review]
