### PR TITLE
style(): fix grid so that the gaps are not clickable

### LINKED ISSUE #621: This area should not be clickable
Here:
image-2

The space block link should not include space between blocks

### PR DESCRIPTION
**Pull request by harshmaur**
Fixes #621

Changes proposed in this pull request:
- Use flex-wrap approach instead of margin-right with float left.

### CODE REVIEW

File: src/views/Home.vue [hunk 1]
```diff
@@ -54,18 +54,20 @@ const { endElement } = useScrollMonitor(() => (limit.value += loadBy));
...
+          class="flex md:flex-1 lg:flex-1 min-w-[200px] w-full"
           @click="
             $router.push({ name: 'proposals', params: { key: space.id } })
           "
           v-for="space in orderedSpaces.slice(0, limit)"
           :key="space.id"
         >
-          <div class="w-full lg:w-1/4 pr-4 float-left">
+          <div class="w-full">
+            <!-- Added mb-0 to remove mb-4 added by block component -->
```
Comment (bonustrack) [inline src/views/Home.vue:67]: Can you remove this comment?

**Review by samuveth — COMMENTED** [review]
Great solution @harshmaur!

File: src/views/Home.vue (hunk 1 above)
Comment (harshmaur) [reply src/views/Home.vue:67]: I could, but I wanted to keep it as it's explicit and anti-pattern. If there's a way to add a comment which gets removed while compiling, I can try doing that. I do not know how.

**Review by bonustrack — APPROVED** [review]
